name: gogle_sheet_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  http: ^1.3.0
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.2
  googleapis_auth: ^1.6.0
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
