// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnL9Qc3ig_g2uHJoYzDKqEV0nCzJqwYDQ',
    appId: '1:727291293346:web:5aea50bf6ecc43bae2b1fb',
    messagingSenderId: '727291293346',
    projectId: 'sheet-test-f392a',
    authDomain: 'sheet-test-f392a.firebaseapp.com',
    storageBucket: 'sheet-test-f392a.firebasestorage.app',
    measurementId: 'G-5P6MYDWEGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2n3YCqQST8OxBAe9iv1CF6wsq4N_6zg',
    appId: '1:727291293346:android:ea01a72a3c3d7c34e2b1fb',
    messagingSenderId: '727291293346',
    projectId: 'sheet-test-f392a',
    storageBucket: 'sheet-test-f392a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepQNxBnE2mCC0QmiLn0d-VEFMrdcMpPE',
    appId: '1:727291293346:ios:8d20756264842762e2b1fb',
    messagingSenderId: '727291293346',
    projectId: 'sheet-test-f392a',
    storageBucket: 'sheet-test-f392a.firebasestorage.app',
    iosBundleId: 'com.example.gogleSheetTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepQNxBnE2mCC0QmiLn0d-VEFMrdcMpPE',
    appId: '1:727291293346:ios:8d20756264842762e2b1fb',
    messagingSenderId: '727291293346',
    projectId: 'sheet-test-f392a',
    storageBucket: 'sheet-test-f392a.firebasestorage.app',
    iosBundleId: 'com.example.gogleSheetTestProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnL9Qc3ig_g2uHJoYzDKqEV0nCzJqwYDQ',
    appId: '1:727291293346:web:32d720fba8cc3636e2b1fb',
    messagingSenderId: '727291293346',
    projectId: 'sheet-test-f392a',
    authDomain: 'sheet-test-f392a.firebaseapp.com',
    storageBucket: 'sheet-test-f392a.firebasestorage.app',
    measurementId: 'G-SVTS0DB2N4',
  );
}
